#!/bin/bash

cd Average
  echo "Average/mean_deriv_check.py ...";           python mean_deriv_check.py --testrun
  echo "Average/convergence_speed_gnc.py ...";      python convergence_speed_gnc.py --testrun
  echo "Average/majorize.py ...";                   python majorize.py --testrun
  echo "Average/majorize_examples.py ...";          python majorize_examples.py --testrun
  echo "Average/solve_average.py ...";              python solve_average.py --testrun
  echo "Average/mean_check.py ...";                 python mean_check.py --testrun
  echo "Average/student_t_solver.py ...";           python student_t_solver.py --testrun
  echo "Average/robust_solver.py ...";              python robust_solver.py --testrun
  echo "Average/welsch_solver.py ...";              python welsch_solver.py --testrun
  echo "Average/welsch_efficiency.py ...";          python welsch_efficiency.py --testrun
  echo "Average/flat_welsch_solver.py ...";         python flat_welsch_solver.py --testrun
  echo "Average/pseudo_huber_solver.py ...";        python pseudo_huber_solver.py --testrun
  echo "Average/geman_mcclure_solver.py ...";       python geman_mcclure_solver.py --testrun
  echo "Average/gnc_irls_p_solver.py ...";          python gnc_irls_p_solver.py --testrun
  echo "Average/trimmed_mean_efficiency.py ...";    python trimmed_mean_efficiency.py --testrun
  echo "Average/winsorised_mean_efficiency.py ..."; python winsorised_mean_efficiency.py --testrun
cd ..

cd LineFit
  echo "LineFit/line_fit_solver.py ...";            python line_fit_solver.py --testrun
  echo "LineFit/line_fit_convergence_speed.py ..."; python line_fit_convergence_speed.py --testrun
  echo "LineFit/line_fit_param_plot.py ...";        python line_fit_param_plot.py --testrun
cd ..

cd TRS
  echo "TRS/trs_solver.py ...";            python trs_solver.py --testrun
  echo "TRS/trs_convergence_speed.py ..."; python trs_convergence_speed.py --testrun
  echo "TRS/trs_derivative_check.py ...";  python trs_derivative_check.py --testrun
cd ..

cd Point3DRegistration
  echo "Point3DRegistration/registration_solver.py ...";      python registration_solver.py --testrun
  echo "Point3DRegistration/registration_deriv_check.py ..."; python registration_deriv_check.py --testrun
cd ..
